apiVersion: v2
name: minecraftcultsite
description: This is the Django app behind www.theminecraftcult.com
type: application
version: 1.2.9
appVersion: 1.0.0
annotations:
  title: The Minecraft Cult Site
maintainers:
  - name: Tyler
    url: https://www.tymler.com/
icon: https://raw.githubusercontent.com/tylerb153/Minecraft-Cult-Website-Django/3ebfb971f3fac0db722b4c950133b4a6e873c4e7/Minecraft-Cult-Website/minecraftcultsite/static/images/LogoColor.svg
home: https://www.theminecraftcult.com/
sources:
  - https://github.com/tylerb153/Minecraft-Cult-Website-Django/
