apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DJANGO_SECRET_KEY
              value: "{{ .Values.djangoSecretKey }}"
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: media
              mountPath: /app/media
            - name: db
              mountPath: /app/db
      volumes:
        - name: media
          hostPath:
            path: "{{ .Values.mediaPath }}"
            type: DirectoryOrCreate
        - name: db
          hostPath:
            path: "{{ .Values.dbPath }}"
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
# -----------------------------------------------------------------------------